version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rag-postgres
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
      POSTGRES_DB: ragdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rag-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: ./
    container_name: rag-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://username:password@postgres:5432/ragdb
      - API_KEY=storage-api-key
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=100
    depends_on:
      - postgres

  python-retriever:
    build: ../python-retriever
    container_name: rag-retriever
    ports:
      - "8001:8001"
    volumes:
      - chromadb:/app/chroma

  rag-gateway:
    build: ../rag-gateway
    container_name: rag-gateway
    ports:
      - "3001:3000"
    depends_on:
      - backend
      - python-retriever
    environment:
      STORAGE_API_KEY: storage-api-key
      STORAGE_API_URL: http://backend:3000
      GROQ_API_KEY: your-groq-api-key
      PYTHON_RETRIEVER_URL: http://python-retriever:8001


volumes:
  pgdata:
  chromadb:

